### ISSUE TITLE
Mac Build Fails

### ISSUE THREAD

**Issue by BlackRookSix** [RhostMUSH/trunk#10]
make[1]: [../bin/netrhost] Error 1 (ignored)
gcc  -g -DBSD_LIKE -DSYS_MALLOC -DSYSWAIT -DBROKEN_NDBM -DBROKEN_ERRNO_SYS -DBIT64 -DC_SUB  -DPCRE_BUILTIN -DSECURE_SIDEEFFECT -DOLD_SETQ -DBANGS -DMARKER_FLAGS -DZENTY_ANSI -DEXPANDED_QREGS -DREALITY_LEVELS -DATTR_HACK -DPROG_LIKEMUX -DPLUSHELP -DUSECRYPT -DSOFTCOM -DMUX_INCDEC -DTINY_U -DUSE_SIDEEFFECT -Wall -DHAS_OPENSSL  -DMUSH_BUILD_DATE="\"`cat date.txt`\"" -DRWHO_IN_USE   -DCACHE_OBJS -I../hdrs   -o ../bin/netrhost door.o shs.o mushcrypt.o news.o mail.o mailfix.o debug.o senses.o create.o game.o help.o look.o match.o move.o player.o predicates.o rob.o set.o speech.o wiz.o walkdb.o timer.o boolexp.o log.o cque.o unparse.o eval.o command.o wild.o netcommon.o functions.o vattr.o db.o db_rw.o compress.o stringutil.o object.o conf.o flags.o htab.o compat.o file_c.o player_c.o bsd.o alloc.o autoreg.o levels.o local.o utils.o pcre.o pcre_extensions.o tprintf.o sha1.o 64btime.o sqlite.o     udb_ocache.o udb_ochunk.o udb_obj.o udb_misc.o rwho_clilib.o  version.o -L./gdbm-1.8.3/.libs/ -lgdbm_compat -L./gdbm-1.8.3/ -lgdbm -lm -lresolv  -lcrypto -lssl -lpcre
<............ a huge amount of 'duplicate symbol' error output..............>
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../bin/netrhost] Error 1
make: *** [source] Error 2

I have the entire output logged but github doesn't allow attachments of type txt.
Let me know what sorts of package information you might need.

**Comment by mrsenile** [comment]
I've been able to compile it clean with Lion, but it does have some issues with clang and the latest OSX (though I've not tried Yosimite).

Of note, GCC and the latest OSX works fine.

**Comment by mrsenile** [comment]
Found the annoying little bug.

With regards to Mac OSX 10.8+ clang with it's included linker did not inline ctype.h properly which caused duplicate entries.  This is proven as gcc does it properly with its own linker fine.

Enforcing ctype.h was no longer inlined resolved the issue.

This compiles now on Maverick and Yosemite.
