### ISSUE TITLE
multi-number subtract for strfunc()

### ISSUE THREAD

**Issue by ray73864** [RhostMUSH/trunk#11]
Would love to have a multi-number subtract for the strfunc() function, much like how there is already a multi-number addition.

Basically: strfunc(sub, 1 2 3 4)

**Comment by mrsenile** [comment]
This was a limitation with sub.

Strfunc takes only as many arguments the functions it calls can take.  In this case, sub, div, fdiv, etc only handled 2 args.  I've recently changed that.

The latest git repo should have all of this updated.  ./patch.sh from the Server directory and you should be in business.
