### ISSUE TITLE
SPEECH_PREFIX/SUFFIX swallow unicode characters

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#111]
This gives me a blank prefix, and not a bright yellow line: `&speech_prefix me=%x0xe2────────%xn%r`

The yellow line shows if I slap a `think` in front of it, so it's not a toggle on my bit or a problem with my client.

**Comment by mrsenile** [comment]
I'm still currently playing with the raw-mode in my own branch but I have a fix if Ambrosia would like to add it.

In two sections in game.c you'll see a line:
                       raw_notify(target, vap[0], port, 1);

This needs to be modified to:
                    if ( UTF8(target) ) {
                       raw_notify(target, vap[2], port, 1);
                    } else if ( Accents(target) ) {
                       raw_notify(target, vap[1], port, 1);
                    } else {
                       raw_notify(target, vap[0], port, 1);
                    }

**Comment by mrsenile** [comment]
Whatcha know, my game.c was inclusive enough I could push the changes.

So fix pushed.
