### ISSUE TITLE
Compilation Warnings and errors I found, but don't know how to fix

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#119]
https://gist.github.com/warmstarter/6b3aa1ad19131e99551d78b52cd5e1f5

https://gist.github.com/warmstarter/89bf4010a07662f30f6a8a6f4ea5741e

**Comment by warmstarter** [comment]
pull request 121 and 122 fixes some of these, so make sure to check those out before looking into this. What remains I really don't know how to fix, but I'm curious to see how they get fixed, so please keep me posted.

**Comment by Chalice** [comment]
Fixed the second gist a few comments back. I'll take a peek at the first.

**Comment by mrsenile** [comment]
It's been 2 years so I'll assume this has been cleaned up.

We should go through all the code and test on various platforms and do further cleanup where required anyway as an on-going job.

New compilers, new cleanup.  Neverending battle.
