### ISSUE TITLE
Information on non-changeable compilation options

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#123]
I think it would be useful to have documentation on compilation options (make confsource) that cannot be easily changed. By this I mean that is a server with a certain set of options is used to start a game and a database, are there any compilation options that could be later enabled or disabled that would cause problems?

Obviously if you use Side Effect functions and then compile without them, they'll stop working. I think something like that is pretty self-evident but various password and database options might be a problem. What if you reduce the LBUF size, but have things in your database that are already beyond that?

Then if there are such potential problems, it might eventually be good to have scripts to adjust the database.

The answer might be that any of these things can be changed with no problems at all. Even that information would be good to have, as it makes people secure in making changes they might be otherwise worried about.

**Comment by mrsenile** [comment]
When you specify the 'i'nformation option to the compile build script it gives details on what each option does and any concerns regarding those options.

If you shrink an LBUF for example it states that information stored can be cut off on load, but it won't damage the db beyond that.
