### ISSUE TITLE
minor listtags() bug

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#127]
How to recreate:
Add a tag to an object, add a second tag to an object, listtags() on the object

What you should be seeing:
There will be a superfluous space at the beginning of the remaining tag.

This example is coming from my a quickie softcoded @tag/list I made, and watched this appear after I went to fix a typo.

```
#201  | Admin Object                   |  admin-obj
#202  | File Object                    | file-obj
```

Code that had generated it:

```
@pemit %#=[repeat(-,78)]%r[ljust(DBRef,5)] | [ljc(Name,30)] | Tags%r[repeat(-,78)];@dolist [search(type=object)]=@pemit %#=[ljust(##,5)] | [ljc(name(##),30)] | [listtags(##)]
```

**Comment by warmstarter** [comment]
Not sure if anything was done on this, but checking the command again today, the issue disappeared. Some sort of caching or delayed processing? Up to you if you think this is worth checking out or is expected behavior.

**Comment by mrsenile** [comment]
I'm marking this closed as it hasn't been able to be reproduced.  

Assuming (I know, bad bad) that it was fixed in later merges and code cleanup.
