### ISSUE TITLE
Medusa Object Install

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#132]
I did a slightly manual install of the medusa object, doing the initial create myself and then install some locks and such first via @mabrosia's +supersafe command.

When I went to install the rest of the object, it didn't work and I had to manually change the name to the dbref#.

It's possibly I'm doing something wrong here, but also possible there's something wrong in the install. Thiis is unrelated to the latest pull request I made on the object which was solely in the comments, and I also didn't use that variant to do the install.

I can't figure out what the error might be. If it's in the Object installer itself (I've seen problems with the names before) that might be something to look into. If it's something I did wrong, I'd be curious to know what it might be so that I can avoid potential issues in the future. Here's and @decompile of the installed object.

```
@create Global: The Medusa Object=10
@lock Global: The Medusa Object==Global: The Medusa Object
@lock/EnterLock Global: The Medusa Object==Global: The Medusa Object
@lock/GiveLock Global: The Medusa Object==Global: The Medusa Object
@lock/LeaveLock Global: The Medusa Object==Global: The Medusa Object
@lock/LinkLock Global: The Medusa Object==Global: The Medusa Object
@lock/ParentLock Global: The Medusa Object==Global: The Medusa Object
@lock/ReceiveLock Global: The Medusa Object==Global: The Medusa Object
@lock/DropLock Global: The Medusa Object==Global: The Medusa Object
@lock/TeloutLock Global: The Medusa Object==Global: The Medusa Object
@lock/TportLock Global: The Medusa Object==Global: The Medusa Object
@lock/UseLock Global: The Medusa Object==Global: The Medusa Object
@lock/OpenLock Global: The Medusa Object==Global: The Medusa Object
@lock/DropToLock Global: The Medusa Object==Global: The Medusa Object
@lock/GiveToLock Global: The Medusa Object==Global: The Medusa Object
@lock/GetFromLock Global: The Medusa Object==Global: The Medusa Object
@Aconnect Global: The Medusa Object=@swi/f [!!and(wildmatch(v(sites),lookup_site(%#)),!match(v(exempt),%#))]=1,{@set %#=slave fubar}
@Adisconnect Global: The Medusa Object=@swi/f [!!wildmatch(v(sites),lookup_site(%#))]=1,{@set %#=!slave !fubar}
@Startup Global: The Medusa Object=@dolist search(eplayer=[lit([hasflag(##,guest)])])={@swi/f [hasflag(##,connect)]=0,@set ##=!fubar !slave}
&VERSION Global: The Medusa Object=1.0.0 07/18/2017
@rxlevel Global: The Medusa Object=Real Admin All
@txlevel Global: The Medusa Object=
@set Global: The Medusa Object=INDESTRUCTABLE DARK SAFE UNFINDABLE NO_COMMAND
```

**Comment by mrsenile** [comment]
This is what occurred when I tried to load the object as stated:

`
Global: The Medusa Object has arrived. (Non-Listening)
Global: The Medusa Object created as object #17334
Locked - Global: The Medusa Object/defaultlock
Locked - Global: The Medusa Object/enterlock
Locked - Global: The Medusa Object/givelock
Locked - Global: The Medusa Object/leavelock
Locked - Global: The Medusa Object/linklock
Locked - Global: The Medusa Object/parentlock
Locked - Global: The Medusa Object/receivelock
Locked - Global: The Medusa Object/droplock
Locked - Global: The Medusa Object/teloutlock
Locked - Global: The Medusa Object/tportlock
Locked - Global: The Medusa Object/uselock
Locked - Global: The Medusa Object/openlock
Locked - Global: The Medusa Object/droptolock
Locked - Global: The Medusa Object/givetolock
Locked - Global: The Medusa Object/getfromlock
Set - Global: The Medusa Object/Aconnect
Set - Global: The Medusa Object/Adisconnect
Set - Global: The Medusa Object/Startup
Set - Global: The Medusa Object/VERSION
Set - Global: The Medusa Object (set RxLevel [again] real)
No such reality level.
Set - Global: The Medusa Object (set RxLevel Umbra Invisible blah bloo ZACK All [again] real)
I don't know what you want to set!
Set - Global: The Medusa Object (set flag INDESTRUCTABLE).
Set - Global: The Medusa Object (set flag DARK).
Set - Global: The Medusa Object (set flag SAFE).
Set - Global: The Medusa Object (set flag UNFINDABLE).
Set - Global: The Medusa Object (set flag NO_COMMAND).

`

**Comment by mrsenile** [comment]
The issue here was you were likely porting the code to somewhere that either didn't have the same reality levels or had different reality levels.

Depending on the level you're at this could cause issues, especially if the realities had different dependencies.
