### ISSUE TITLE
enhancement: elements() with a %r delimiter acts funny

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#138]
So I have a case where I need to grab each "line" of text that is pre-formatted. elements() leaves the delimiter in if it's %r. e.g.:
```
> @fo me=&test me=this is%%ra test
> think elements( v(test), 2, %r )

a test
```
That space between 'think' and 'a test' is literal. It's a %r.

This is not the usual behavior of elements(). e.g.:
```
> think elements(this|is|a|test, 2, | )
is
```
No delimiter!

Thanks.

**Comment by thenomain** [comment]
I feel like making this its own bug, but this is also frustrating:
```
> think edit( elements( v(test), 2, %r ), %r, )

a test
```
That is, edit() didn't delete the leading %r. 

But edit behaves properly in other situations:
```
> think edit( v(test), %r, %b )
this is a test
```
That is correct!

**Comment by mrsenile** [comment]
%r is 'two' letters, so mid(%r,0,1) or mid(%r,1,1) will work until multi-letter delimiters is available for all functions.

This will be tagged as an enhancement.

**Comment by mrsenile** [comment]
elementsmux() handles multi-arguments now as well as fully ansi aware.
