### ISSUE TITLE
In Ashcom, `-replies clash with commasks

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#139]
If a channel is cloaked so that all users are using a commask, \` replies fall apart.  I presume the code that handles \` doesn't look at masks.

**Comment by stevensmedia** [comment]
On channels where 'real' names are hidden, you don't want to leak that info. It should only operate with masks.

**Comment by mrsenile** [comment]
I'll have to play around with this.  I don't think it's going to be relatively easy to do, but we'll see.

You're right though that it should be done to help masq.

**Comment by mrsenile** [comment]
This has been fixed with 1.3.7 of the comsystem.
