### ISSUE TITLE
Documentation & Suggestion

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#145]
Documentation: Apparently there is a @destroy/purge switch that is not in "help @destroy".

Suggestion: Alias @destroy/instant to @destroy/purge.

Thanks!

**Comment by mrsenile** [comment]
/purge is a wizard only option (it bypasses the recover list) so /purge is in 'wizhelp @destroy'

**Comment by thenomain** [comment]
D’oh! Have I mentioned that sometimes I’m a dunce?

Maybe for the document project, “see also wizhelp (foo)” should be added where applicable. Anyway, thanks.

**Comment by Chalice** [comment]
Closing this for now!
