### ISSUE TITLE
MUSQN not being populated unless format setr(d, val, s) is used

### ISSUE THREAD

**Issue by CuAnnan** [RhostMUSH/trunk#147]

**Comment by CuAnnan** [comment]
If this is intended, the docs need to be  updated to reflect this.

**Comment by mrsenile** [comment]
> @admin penn_setq=1
> think [setq(user,test)][execscript(setq.sh)]
MUSH Stuff
MUSHQ_0: test
MUSHQN_0: user
MUSHN_USER: test

MUSHN will only be populated if there's a name assigned to a register.

I can see where the documentation may not be fully clear on it, but it should be understood that if you don't label a register the label wouldn't be utilized as it wouldn't exist.

**Comment by CuAnnan** [comment]
https://github.com/CuAnnan/domain/blob/main/output.txt

Nothing with the musqn_ or mushn_ prefix.

**Comment by mrsenile** [comment]
what does `think config(penn_setq)` return?

**Comment by CuAnnan** [comment]
0

**Comment by mrsenile** [comment]
Turn it on and your issue should be resolved.

Without it enabled, setq(foo,bar) is not setting to the label 'foo' but setting it to register 'f'.

wizhelp penn_setq

**Comment by CuAnnan** [comment]
Thanks. That did it.
