### ISSUE TITLE
lattr() + utf8/accents = sadness

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#153]
@Version info
RhostMUSH version 4.2.1-6 RL(A) # [09/16/2021]
Build date: Tue, 12 Oct 2021 16:26:18 -0400

```
Thenomain types -=> &test_%<u00fc>berness me=Yawp
Set.

Thenomain types -=> ex me/test_*
TEST_%<U00FC>BERNESS: Yawp

Thenomain types -=> think lattr( me/test_* )
TEST_U00FC>BERNESS
```

Since we're going more to UTF8/ACCENTS friendly code, I think this should be looked into.

I don't *need* it, but it'd be fun.

**Comment by mrsenile** [comment]
This is a parsing issue, not an issue with lattr()

`
> think/noansi lattr(me/test_*)
TEST_%<U00FC>BERNESS
`

Also, unicode markup is identified by %<u and not %<U.  It's something that should be considered for compatibility.

**Comment by mrsenile** [comment]
Ambrosia,

Suggested fix:

eval.c, in parse_ansi around line 912:
`                if ( (ToLower(*string) == 'u') &&`

**Comment by thenomain** [comment]
Good to know what the root cause is.

Good seeing you, too, Ash.

**Comment by mrsenile** [comment]
This has been fixed with the latest update.

**Comment by thenomain** [comment]
You are too good for us. Thank you.
