### ISSUE TITLE
guest users and `lastsite`

### ISSUE THREAD

**Issue by asymmetricia** [RhostMUSH/trunk#155]
Guest users expect logins from a variety of sources / IPs. When a new user connects to a Guest, Rhost informs the user of their previous connection host. (Nominally a security mechanism to allow users to detect unauthorized logins?)

However, for guests, this is disclosing other users' IP addresses that were recorded as part of legitimate activity. It would be better if guest users' `lastsite` were cleared at logout.

(observed on `RhostMUSH Alpha version 4.1.0RL(A) patchlevel 2 #5`)

**Comment by mrsenile** [comment]
This will be fixed as soon as Ambrosia merges my changes.

Config parameter to handle it: guest_displaylastsite

Defaults to 'yes' as that was previous existing behavior.

**Comment by mrsenile** [comment]
Also, site information should remain on the guest characters as it gives staff a source of auditing but I agree that guests themselves should not be able to see previous information.

**Comment by mrsenile** [comment]
Verified this has been pushed to master.  Closing.
