### ISSUE TITLE
@rxlevel/@txlevel with following spaces doesn't set

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#156]
Let's say I have privileged code running a @rxlevel, with an optional register (`o`). The reality level "dreaming" is valid.
```
Thenimmain types -=> @rxlevel #6648=!all dreaming %qo
Cleared.
Set.
You must specify a reality level to set.
```
In this instance, @rxlevel does not change.

So I think either the expected behavior is incorrect (following spaces should get stripped first), or the message could be more informative (You must specify a reality level to set. - @rxlevel set to original value.)

Or I don't know how it's supposed to work. Always a possibility.

**Comment by mrsenile** [comment]
This is fixed in my latest branch as soon as Ambrosia merges it.

It also identified a potential memory leak when @rxlevel/@txlevel were fed an invalid argument list

**Comment by mrsenile** [comment]
Verfiied this fix has been pushed to master.  Closing.
