### ISSUE TITLE
bug: register labels lost outside local context?

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#158]
I have some code that sets `setr( f, <code>, found )`. If I call that code with u(), then try to reference `%q<found>` outside the u()-call, I get nothing. However, `%qf` and `[r(found)]` still work.

I have tried this with and without localize() on the called attribute, just in case. 

Example:
```
> think u( #funcs-architect/func_+notes_validate_notes, *target, *bir* zzz, , %b ) %r>> f: %qf -- q<found>: %q<found> -- r(found): [r(found)]

31 32|zzz 
>> f: 31 32 -- q<found>:  -- r(found): 31 32
```

**Comment by thenomain** [comment]
Easy way to replicate:
```
@va me=This is code.[setq( f, I found it!, found )]
think [u( me/va )] >> f: %qf >> q<found>: %q<found> >> r(found): [r(found)]
```

**Comment by thenomain** [comment]
Since it came up in the Discord, let's try a different initial. And yes, penn_setq is enabled, if that's making this work:
```@va me=Hello![setq(g,Can you find me?,found)]
think [u(va)] -- r(found): [r(found)]

Hello! -- r(found): Can you find me?
```

**Comment by mrsenile** [comment]
Er, not sure but I can't reproduce it?  on the Rhost dev server:

`
> @va me=This is code.[setq( f, I found it!, found )]

> think [u( me/va )] >> f: %qf >> q<found>: %q<found> >> r(found): [r(found)]

This is code. >> f: I found it! >> q<found>: I found it! >> r(found): I found it!
`

**Comment by thenomain** [comment]
I had *just* updated my test server. I updated again and this is working now.

Thanks for prodding at it.
