### ISSUE TITLE
Request: sudo()

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#160]
What @sudo is, but for function code.
(aka, Mux's objeval().)

`sudo( <target>, <function code> )` would run \<function code> with all of the information of \<target>, assuming control over <target>. %# would be \<target>, %@ and %! would remain the same (I think?), registers would be passed, but ultimately it would be as if \<target> was running the code.

**Comment by thenomain** [comment]
Through shenanigans and checking, Ashen has proven the following is safe:
```
objeval( *bob, objeval( *bob, move( exitname )))
```
Which is what I'd like. Not "pretend" you're running code as if you were someone else, actually run that code as someone else, their permissions, their location, them if it's side-effect, all of it.

I understand Ash is adding this as a flag to objeval() now that we're in concordance.

**Comment by mrsenile** [comment]
This added with objeval(foo,bar,2)

```
  The following permission overrides are allowed as a bitmask.
    1 - Wizard only, will override the NO_CODE flag on the target and still 
        execute any code of that person.  This is ignored for any enactor 
        not a wizard.
    2 - Guildmaster and higher only.  Will enforce player, cause, and caller
        as the <thing> as a 'true' sudo to that target for the <function>.
```
