### ISSUE TITLE
utfcode conversion change request

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#161]
`═` is 0x2550, currently being converted to '-'. Please convert to '='.

`–` is 0x2012 and `—` is 0x2014, not currently being converted. Please convert these to '-'.
(Might as well put 0x2013, `–` in that, too.)

Thanks!

**Comment by thenomain** [comment]
Location reference:
https://github.com/RhostMUSH/trunk/blob/master/Server/src/stringutil.c#L2054

**Comment by Chalice** [comment]
Done!
