### ISSUE TITLE
bug: stringutil.c has more characters in UTF8 fallback now

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#162]
https://github.com/RhostMUSH/trunk/blob/5cddce3a5e0b5bf150f58c22c7083aa835d2b29f/Server/src/stringutil.c#L2094

You now have 268 entries in the array.

**Comment by mrsenile** [comment]
This was fixed in https://github.com/RhostMUSH/trunk/commit/05fdec0d11ee8b015ab3f416e6bad839e3c318a2
