### ISSUE TITLE
Request: single-line reply with BRANDYMAIL active

### ISSUE THREAD

**Issue by HarukaWatanabeLA** [RhostMUSH/trunk#166]
Per `help MAIL SEND QUICK` we can send a mail quickly like so:

`mail/send Polk Ambrosia=Hi//This is a mail I'm sending`

This works regardless of one's BRANDY_MAIL (or presumably PENN_MAIL) setting. But there's  no equivalent for doing a mail reply.  The only way to do a quick reply is to turn off BRANDY_MAIL and do:

`mail/reply @1=Can I Reset my password?`

Maybe mail/reply/send should work regardless of your toggles or something

**Comment by mrsenile** [comment]
This has been added with my branch 2d98b40fa5f2e4444c04c121ca1affda136fdce5
