### ISSUE TITLE
Feature Request: stripUTF8()

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#179]
A function, stripUTF8(), that acts exactly like stripaccents().

Thanks!

**Comment by mrsenile** [comment]
This was done as stripunicode a while ago, and remodified to be an alias to stripaccents as accents now handle utf8/unicode

Code modificed per branch: https://github.com/RhostMUSH/trunk/commit/9fb296aca0a5e9c6444ea0db4249b445917cc2df

Code replaced from hardcoded function to alias: https://github.com/RhostMUSH/trunk/commit/bae0235cff55c99cf5c62de5ea04d82758d8ccfe

Old Rhost's make sure you have the alias in your alias.conf file:
function_alias  stripunicode    stripaccents
