### ISSUE TITLE
Bug: KEEPALIVE pings are sent raw over websocket

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#180]
If a player who has KEEPALIVE on is connected on a websocket, the websocket receives raw KEEPALIVE pings. This generates invalid UTF8 strings and makes a browser freak out and kill the connection.

Those KEEPALIVEs (and really any invalid UTF8 strings) should be filtered out before being sent.

Honestly ACCENTS users are hosed but who uses ACCENTS?

**Comment by Chalice** [comment]
Merged!
