### ISSUE TITLE
KEEPALIVE @toggle on Potato client

### ISSUE THREAD

**Issue by BlackRookSix** [RhostMUSH/trunk#19]
The Potato client has an issue with the keepalive packet sent by Rhost.  The maker of Potato is aware of the issue.  

Symptoms/Recreate:  
@toggle me=KEEPALIVE
( wait a few minutes )
> :tests.
ÿñRook tests.

**Comment by mrsenile** [comment]
This is something that only effects the potatoe client, thus is an issue with the client.
