### ISSUE TITLE
Bug: runintz(), timefmt( $I ), and BSD

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#191]
Apparently this only breaks in BSD-related OSes, like Darwin or FreeBSD.

```
think runintz( EST, timefmt( $I, secs() ))
0

think timefmt( $I, secs(), EST )
-18000
```

Something something the way BSD does time being a pain.

**Comment by mrsenile** [comment]
This is fixed with https://github.com/RhostMUSH/trunk/commit/5f63834be5c739da6f19581348bfca67d111a4ba
