### ISSUE TITLE
attrcnt() in Rhost is not like attrcnt() in TinyMUX

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#196]
In TinyMUX, attrcnt allows pattern matching, which is great for say counting just the data* attributes in an object. This is not possible in attrcnt() in Rhost.

help attrcnt() (in TinyMUX)
ATTRCNT()

  FUNCTION: attrcnt(&lt;object>[/&lt;wild-pattern>])

We have softcoded this in Rhost with:
FUN__ATTRCNT(#13033): [words(lattr(%0))]

But it would be nice if attrcnt() was compatible

**Comment by mrsenile** [comment]
This has been added with https://github.com/RhostMUSH/trunk/commit/9aa777526b7a66d0cdc533f36bbf71b3f34ee016
