### ISSUE TITLE
In the Converter: Created and Modified Dates are swapped

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#197]
What is stored as the Created and Modified dates in TinyMUX are coming through incorrectly swapped into the ModifiedStamp and CreatedStamp on all items: players, rooms, exits and objects.

**Comment by Hope-Shangrila** [comment]
I can confirm this is now correct.

**Comment by mrsenile** [comment]
This has been fixed with https://github.com/RhostMUSH/trunk/commit/391bd8ff9b7f22ae9138cb8eb2affba07cc8068e
