### ISSUE TITLE
In the Converter: Conninfo is not being ported

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#198]
ConnInfo: 147403288 2043841 133444 567 1708857640

This is an attribute in TinyMUX that we use extensively. It includes these:
//     Total online time
//     Longest connection duration
//     Duration of last connection
//     Total number of connections.
//     time (time_t) of last logout.

We need these to come across to retain the history of the character as well as display these values or do clean-up based on these values.

So we are also likely to need some/all of the functions related to accessing the data held in this attribute.

**Comment by mrsenile** [comment]
This has been added with https://github.com/RhostMUSH/trunk/commit/695f8eed72d2f927a8335b3375331f39e7c76351
