### ISSUE TITLE
%_<-> trace stack popping

### ISSUE THREAD

**Issue by ixokai** [RhostMUSH/trunk#20]
I'm wondering if it would be possible to do like %_<-> to pop off the trace stack the most recent addition? My code with %_<>s is becoming very verbose, partly because I prefer longer labels in debugging to make it clear, so having to insert %_attribute:task then %_<-attribute:task> repeatedly adds a LOT of noise. 

If I could do %_attribute:taskcodecode%_<-> it'd be great.

**Comment by mrsenile** [comment]
%_<-> Added to 3.9.5p4.

Also altered substitutions so that if you have multiple labels, %_<-blah> removes the LAST 'blah' defined, before it removed the first one, which made no sense.
