### ISSUE TITLE
Leading zeros on time/date for compatibility

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#201]
Add a configuration parameter to include the leading zero on date/time for compatibility. DD and YY especially are suppressing zeroes in convsecs(). Ashen-Shugar's comment: "should be added to convsecs() and time()"

**Comment by mrsenile** [comment]
Added with https://github.com/RhostMUSH/trunk/commit/50cc1fc3681a2ae760e84012b51eadd8b4b567a2

This is a config param to enable this feature
