### ISSUE TITLE
Help Files: Please mention 'help bittype'

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#203]
Could someone add "help bittype()" to the 'see also' list in the following help files:

immortal
super-royalty
royalty
councilor
architect
guildmaster
wizards

Probably some others, but as I can never remember the order in which the bit types cascade, and as far as I know it's only in `help bittype()`, that would help me and hopefully others. 

Thanks.

**Comment by mrsenile** [comment]
Handled with commit https://github.com/RhostMUSH/trunk/commit/c0277375079bfd2117f052dadb20fd571a96617b
