### ISSUE TITLE
"home" command

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#205]
This was changed for us recently in TinyMUX. The "home" command is super spammy, producing 3 lines of emits and then a "look" of the room... even when you are already home. So change "home" to check first and report "You are already home." if the player is home.

When a player in a BLIND room types "home" (regardless of where their home is) other people in the room see "name
 goes home." We don't want this, the room is BLIND. BLIND should be suppressing arrival and leaving messages.

**Comment by mrsenile** [comment]
This was updated with the latest push.  Good catch on the blind issue.
