### ISSUE TITLE
bug: stripunicode() is no longer aliased to stripaccents()

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#207]
```
> think [stripaccents(hüllo)]
hullo

> think [stripunicode(hüllo)]
#-1 FUNCTION (stripunicode) NOT FOUND

> help stripunicode()
STRIPUNICODE()
  Function: stripaccents(<string>)
            stripunicode(<string>)
<etc.>
```

Thanks.

**Comment by mrsenile** [comment]
it's part of the alias.conf
# grep stripunicode alias.conf
function_alias  stripunicode    stripaccents

Just add that entry in your alias.conf and you're golden.  It's part of the distro for a while, but likely your alias.conf just wasn't updated is all.
