### ISSUE TITLE
wizhelp connect_methods 'see also' mispelling

### ISSUE THREAD

**Issue by obsidwolf** [RhostMUSH/trunk#209]
Smallest of things...

The see also mentions account management, however it's currently 'wizhelp account membership'

Ashen must've had too much wine when writing again

--Hige/Alpha

![image](https://github.com/RhostMUSH/trunk/assets/162399963/b41d72c6-a76e-49e6-9f0a-2d9b27f14cb2)

**Comment by mrsenile** [comment]
Fixed with https://github.com/RhostMUSH/trunk/commit/fffbb200da805d18f8c2f878ec8ac19142ebf6ea
