### ISSUE TITLE
Inzone enhancement

### ISSUE THREAD

**Issue by Hope-Shangrila** [RhostMUSH/trunk#211]
inzone() returns the rooms in a zone. This is great for a zone being used to share 'local' commands across multiple rooms, but completely ignores the alternative use of zones to allow players to share editing control with the enterlock, where the zone contains rooms and exits and sometimes even objects. Can we have a method to find all the items in a zone, rather than just the rooms?

**Comment by mrsenile** [comment]
lzone() handles all item types in a zone, zlcon() (recent addition) handles all items residing inside a zone
