### ISSUE TITLE
Invalid clean up in order for MySQL to correctly deal with Single-result Stored Procedures

### ISSUE THREAD

**Issue by HarryCordewener** [RhostMUSH/trunk#28]
MySQL will get out of sync with MySQL as it doesn't clean up properly after running a stored procedure.
The following articles are related.
http://t.pennmush.org/Me0TkV
http://t.pennmush.org/Me7Ild
http://t.pennmush.org/Me7Db8

Steps to Reproduce:

Create a Stored Procedure.
Run the Stored Procedure twice from RhostMUSH.
Note that the second run has an error claiming the commands are out of sync. (Requiring @shutdown/reboot to resolve.)

----

NOTE: This has not been tested in RhostMUSH, this is based on an issue found in PennMUSH, though I'm 95% certain, as they _build_ off of the same sql.c, they have the same defect. Blame Ashen-Shugar, he told me to post this.
See: https://github.com/pennmush/pennmush/issues/1100
A fix is also bound to that issue, in case you want to take a look.

----

For the Stored Procedure I used to test this, check out:
http://mush-mercutio.tumblr.com/post/153345784737/pennmush-graph-framework

**Comment by mrsenile** [comment]
this has been fixed with the latest 4.0.0p1 code.
