### ISSUE TITLE
Time is not flowing smoothly in 1fe1141d8492fdb502050ad4048495b2d2aa03a1

### ISSUE THREAD

**Issue by pdbogen** [RhostMUSH/trunk#3]
In 1fe1141d8492fdb502050ad4048495b2d2aa03a1, time does not flow smoothly; secs() stops incrementing for a time, then resumes. e.g.:

(these were run every 1s by my client, just a "think [secs()]")

1422058296
1422058297
1422058298
1422058299
1422058300
1422058301
1422058302
1422058303
1422058304
1422058305
1422058306
1422058307
1422058308
1422058309
1422058310
1422058311
1422058312
1422058313
1422058314
1422058315
1422058316
1422058317
1422058318
1422058319
1422058320
1422058321
1422058322
1422058323
1422058324
1422058325
1422058326
1422058327
1422058328
1422058329
1422058330
1422058331
1422058332
1422058333
1422058334
1422058335
1422058336
1422058337
1422058338
1422058339
1422058340
1422058341
1422058342
1422058343
1422058344
1422058345
1422058346
1422058347
1422058348
1422058349
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350
1422058350

**Comment by mrsenile** [comment]
Can not reproduce issue.

There is some methods where Rhost will re-sync itself to the server hosting it if the time becomes skewed, but that's usually a +/- 2 minute window so it's not always reskewing time.

See if this is reproducible to the latest branch, and if so please re-open.
