### ISSUE TITLE
4 byte utf8 sequences bugged

### ISSUE THREAD

**Issue by spijdar** [RhostMUSH/trunk#31]
There are two bugs I found in the handling of utf8 sequences that require 4 bytes, the ones formatted like `%<u12345>`.

One is in stringutil.c, utf8toucp, in the base conversion. The last subexpr should be added, not subtracted. Here's a fix: http://repo.paperfox.es/eery/rhostmush/.git/tree/Server/src/stringutil.c?h=alpine#n1953

A second is in eval.c, parse_ansi. s_ucpbuf is nulled out only once - it can take code points either of the form u1234, u12345, or u123456. But since the buffer is only cleared at the start, if a longer codepoint is processed, the last one or two characters get stuck in the buffer and corrupt any other codepoints processed. 

After reading in the codepoint something like `s_ucpbuf[i_utfcnt] = '\0';` should be added, like at http://repo.paperfox.es/eery/rhostmush/.git/tree/Server/src/eval.c?h=alpine#n872

**Comment by Chalice** [comment]
Fixes have been applied to the Master branch :)
Thank you very much!
