### ISSUE TITLE
TwinkLock and control

### ISSUE THREAD

**Issue by ixokai** [RhostMUSH/trunk#33]
Okay, so. I have a twinklock on a room. its IS_PLANNED/1, where IS_PLANNED is [faction-in(code,%#)] ... it works just fine. BUT. I have a wizard-owned, inherit object that is doing get(#1234/region) and its returning blank. If I change the twinklock to $#3|IS_PLANNED/1 it works again. I think the twinklock is somehow interfering with the control in my code. (Even with the original lock my wizard can ex and edit the room as appropriate. Its just my inherit-code that seems unable to.)

**Comment by mrsenile** [comment]
This was fixed in Rhost 4.0p1.  Good catch.
