### ISSUE TITLE
Ashcom tests for patchlevel 

### ISSUE THREAD

**Issue by CharlyLeetham** [RhostMUSH/trunk#36]
Line 17 of trunk/Mushcode/comsys runs Test 2 that tests that a minimum patch level of Rhost is installed.
The code currently tests for Patch Level 13 ([gt(after(version(),patchlevel),13)])
The current version of Rhost is 4.0.0RL(A) so the test fails.

**Comment by mrsenile** [comment]
This will be fixed in Version 1.2.2.  Good catch.
