### ISSUE TITLE
Ashcom Notify on Channels 

### ISSUE THREAD

**Issue by CharlyLeetham** [RhostMUSH/trunk#37]
When Aschom is installed it installs the PUBLIC and NEWBIE channels.

This appears to 'break' the @comcfg/notify -Public command.
When that command is used, the PUBLIC channel still gets notifications.
@comcfg/notify -Newbie turns notifications off on the PUBLIC channel.

Deleting the NEWBIE channel resolves this issue.

**Comment by mrsenile** [comment]
You have the syntax reversed to how it's intended.

Per the help:

ComSys: WizHelp for version 1.2.0 of AshComV2 [09/22/2017]
------------------------------------------------------------------------------
Syntax: comcfg/notify +<0 or channel name>
        comcfg/notify -<0 or channel name>
        comcfg/notify list

The first syntax allows you to specify what channels are NOT allowed
to broadcast player connects/disconnects. Specifying '0' means all channels.

The second syntax allows you to specify what channels ARE allowed
to broadcast player connects/disconnects. Specifying '0' means all channels.

The third syntax shows the current channel(s) that are broadcasting on the channel.

You can type @clist/notify to see what channels are doing notifications.
------------------------------------------------------------------------------
ComSys: Individual Topic WizHelp completed.


The current clist/notify:

... Channel                     Notify    Broadcast
    Newbie                      enabled  enabled
    Public                      enabled  enabled
    Xyzzy                       enabled  enabled
---- End of list of channels ----


Meaning, when you do:
comcfg/notify -Public

It is actually removing 'Public' from the list of channels set to be ignored from notifying.

Now, when you do:
comcfg/notify +Public

It is applying a reverse-logic.  It specifies that channels are to be allowed to be notified, **if they exist in that list**, and sets all channels NOT in the list to be ignored.  The exception to this is if you specify '0' (+0) it assumes you want no channels broadcasting and turns it off entirely.

See the list it shows:*** Channel                     Notify    Broadcast
    Newbie                      IGNORED   IGNORED
    Public                      enabled   enabled
    Xyzzy                       IGNORED   IGNORED

Now let's assume I want to also allow newbie to broadcast:
comcfg/notify +Newbie

*** Channel                     Notify    Broadcast
    Newbie                      enabled   enabled
    Public                      enabled   enabled
    Xyzzy                       IGNORED   IGNORED

Now, let's assume I want all channels ignored, so we'll use the +0 override:
comcfg/notify +0

ComSys: Channel 0 has been added from (dis)connect notifications.
*** Channel                     Notify    Broadcast
    Newbie                      IGNORED   IGNORED
    Public                      IGNORED   IGNORED
    Xyzzy                       IGNORED   IGNORED



There is a small bug that seems to want to make it case sensitive for checking, which I have fixed as well.
