### ISSUE TITLE
@door socket across reboots?

### ISSUE THREAD

**Issue by captdeaf** [RhostMUSH/trunk#42]
M*U*S*H had an incoming connection via an `@door` from erebor, lasting 4 weeks. It was never recv()'d from after the first usage, and never disconnected or closed. Ashen's initial take is the `@door` socket not being fully cleared during a mush Reboot.

"""
Ashen-Shugar pages: yea, we go through and connect sockets that exist and forcefully 
close others that are not in the list
Long distance to Ashen-Shugar: Walker nods, so the @door probably got skipped somehow?
Ashen-Shugar pages: but likely we need to do some house cleaning on sockets just to make 
sure
Ashen-Shugar pages: yea, it's my thought
Ashen-Shugar pages: do me a favor? Report it as a bug in our github so I don't forget.
You paged Ashen-Shugar with 'Sure thing.'
"""

**Comment by mrsenile** [comment]
Finally got around to cleaning this up.  It should be fixed with the latest git update.
