### ISSUE TITLE
Cloaked Warnings from Timeout

### ISSUE THREAD

**Issue by g33kcub** [RhostMUSH/trunk#47]
When you exceed the timeout, it doesn't tell you once it repeats every few seconds. 

You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.
You have exceeded the timeout and been CLOAKED.

**Comment by mrsenile** [comment]
The only time it should do this is if the target player in question had its DARK and UNFINDABLE flags removed, yet at the same time not had its idle time updated.

Can you provide further information for this use case?
1.  Were you logged in more than once?
2.  What is the value of the config parameter idle_timeout
3.  What is the value of the config parameter idle_interval
4.  Did you set your @timeout value to '1' and not '-1'?

I'm thinking you may have done #4 as that will time you out every second, where -1 disables timeout.

**Comment by mrsenile** [comment]
I still have not been able to ever reproduce this.

Hand walking the code shows it shouldn't be possible short of a timeout value of '1' or a '0'.

Is it possible you can provide more details?

Without further information I'll close the ticket as 'not enough information'.
