### ISSUE TITLE
comsys bug caused by newline typo

### ISSUE THREAD

**Issue by kinostl** [RhostMUSH/trunk#48]
https://github.com/RhostMUSH/trunk/blob/4afd7cb437ba3ca150dc8e6bd2a8a54e52f440ca/Mushcode/comsys#L364

Should be this so that it actually evaluates. (364 and 365 on the same line)

`&DO_TIMEFORMAT ChanFunc=[setq(0,ifelse(hasattr([v(F-DB)]/do_timeformat_%0),ueval(do_timeformat_%0/sub,%1,%2,%3,%4,%5,%6),ueval(do_timeformatgen/sub,%1,%2,%3,%4,%5,%6)))][ifelse(!!$r(0),%q0%b)]`

**Comment by kinostl** [comment]
Just an error with how I imported it into my DB

**Comment by Chalice** [comment]
Merged! :)
