### ISSUE TITLE
Store compile time options / DEFs

### ISSUE THREAD

**Issue by c-hudson** [RhostMUSH/trunk#53]
Store any compile time options / DEFS inside the database. A script could then be created to pull these values out of the database for use in compiling the MUSH. The goal is to make it easier to re-setup a MUSH if the database but not all original files are available.

**Comment by mrsenile** [comment]
This is now available with execscript(config.sh) to load into #1

Then in the 'game' directory there is a config_pull.sh <netrhost.db.flatfile> that will pull the data from a flatfile and populate the compile time options into the default config that will automatically be loaded when you do 'make confsource'.

Enjoy.
