### ISSUE TITLE
Ashcom comnotify/compress toggle bug

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#54]
Run `comnotify/compress` the first time and you get back `comnotify/compress
Comsys: COMNOTIFY -- Compression has been enabled`

That's correct behavior.

Run `comnotify/compress` a second time and you get back `comnotify/compress
Comsys: COMNOTIFY -- Compression has been disabled`

That's also correct.

But running it a third, fourth, fifth... time keeps saying `disabled` instead of ever re-enabling it.

That's the bug.

Ran into this on a game Amb is coding.

**Comment by Chalice** [comment]
Core cause is using wipe() to remove attributes, while set() is being used to set them. wipe() fails often due to SAFE flags if the safe_wipe config param is enabled.

**Comment by mrsenile** [comment]
This has been fixed with the latest update to the comsystem.
