### ISSUE TITLE
Rhost should have a setting to restrict Guest paging

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#55]
Guests sending pages to players are a long standing tool of abuse that rarely have any value.

It should be possible to restrict their ability to page. Only to staff, only to people with certain permissions, flags, or totems.  Or to nobody at all.

**Comment by mrsenile** [comment]
This can be done already with @icmd.

@icmd[/ignore] *guestplayer=page, mpage, rpage
