### ISSUE TITLE
Request: "@name/ansi me=" removes ansified name only

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#62]
```
> @name/ansi me=
Give it what new name?
```
I know the description says that `@name/ansi` runs a few commands, but it might work that if someone tries to set it to "null" what they mean is to simply remove the ANSI/Fancy-Pants version of the name, not their entire name, so the equivalent of `@extansi <target> = `.

Thanks!

**Comment by mrsenile** [comment]
This has been added.  Thanks for the suggestion.
