### ISSUE TITLE
Rhost finding "timeout" for execscript is wonky on macOS

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#63]
Okay, how to describe this. On macOS 10.14 and higher, you can't add a symlink to `/usr/bin/` even with root or sudo. (Link to why later.)

`timeout` exists, it's just in `/usr/local/bin/`

Ambrosia says the code is here:
```
   if ( stat("/usr/bin/timeout", &st_buf) == -1 ) {
      if ( stat("../bin/timeout", &st_buf) == -1 ) {
         safe_str("#-1 /usr/bin/timeout nor local timeout not available.  No safty net for pipe execution.", buff, bufcx);
```
Which means the only macOS solution is: `ln -s /usr/local/bin/gtimeout /your/rhost/Server/bin/timeout`

We think this is wonky and probably can be more generic (the command exists) or possibly more configurable (override where Rhost is looking for the command).

Read the horrors of newer macOS security here: https://stackoverflow.com/questions/36730549/cannot-create-a-symlink-inside-of-usr-bin-even-as-sudo

Thanks!

**Comment by thenomain** [comment]
We, all together, have also discovered that `timeout -9` doesn't work here and `timeout -s 9` does. This is added as a reminder, is all.

**Comment by mrsenile** [comment]
This has been fixed with an upstream push that allows the internal timeout code to work in  BSD-like environments.
