### ISSUE TITLE
Suggestion: Environment variable when using execscript()

### ISSUE THREAD

**Issue by thenomain** [RhostMUSH/trunk#64]
Can we pass some environment/shell variables to scripts called via execscript()?

Do yer magic, Harry.

Thanks!

**Comment by thenomain** [comment]
So Ashen took 5 minutes to make this happen!

And then this happened.

```
Thenomain types -=> think execscript(dw_getstat.py, Feathertop Finch, Strength, Other Magic, 4, 5, 6)
Yup, I can't find argv[2]. argv[1] is: 'Feathertop Finch Strength Other Magic 4 5 6'
```

So now this is a bug. Ambrosia's been made aware.

Whups.

**Comment by mrsenile** [comment]
As far as I'm aware, argv[2] and such never was possible with execscript based entirely on the source.  If you find this is the case ever again please report it as a bug as it should not be the case.
