### ISSUE TITLE
API connections are not processed until after a telnet connection is made

### ISSUE THREAD

**Issue by stevensmedia** [RhostMUSH/trunk#70]
If you've freshly started netrhost, any API connections hang. No log mentions happen, and the connections just do nothing.

However the second you connect to the telnet port, those API connections spring to life, and will show up in the netrhost.gamelog AFTER the mention of the initial telnet port connection. Example from my logs:

```
210316.184555 MagicCityMUSH NET/CONN : [18/localhost] Connection opened (remote port 42558)
210316.184555 MagicCityMUSH NET/CONN : [19/127.0.0.1] Connection opened (remote port 36296)
210316.184555 MagicCityMUSH NET/DISC : [19/127.0.0.1] Connection closed, never connected. <Reason: API Connection>
210316.184555 MagicCityMUSH NET/CONN : [19/127.0.0.1] Connection opened (remote port 36300)
210316.184555 MagicCityMUSH NET/DISC : [19/127.0.0.1] Connection closed, never connected. <Reason: API Connection>
210316.184555 MagicCityMUSH NET/CONN : [19/127.0.0.1] Connection opened (remote port 36302)
210316.184555 MagicCityMUSH NET/DISC : [19/127.0.0.1] Connection closed, never connected. <Reason: API Connection>
```

The 'localhost' connection was made via telnet to the telnet port 30 seconds AFTER the 127.0.0.1 API port connections were made.

This appears to be a long standing bug. It showed up in my game which was running master from May of 2020, and still happens with master from as of when I make this report.  Darren@rhostdev also reports the same issue.  I'm seeing this on Ubuntu 18 LTS, Darren on Ubuntu 20 LTS.

**Comment by mrsenile** [comment]
This should be fixed in the latest Repo.

https://github.com/RhostMUSH/trunk/commit/1a2d1dcc36013336eb91e38ae608673831c4850e
