### ISSUE TITLE
Slowness and freeze of the make

### ISSUE THREAD

**Issue by mdziczkowski** [RhostMUSH/trunk#85]
After starting the compile (running it from the `make confsource` after selecting the options), the make was done very slowly (even if my PC is quite fast one), before it has froze on the line:

> gcc --param ggc-min-expand=0 --param ggc-min-heapsize=8192 -g -DBROKEN_NDBM 
> -DHAVE_ERRNO_H -DBIT64  -DMYSQL_VERSION=\"5.5.58\" -DM_SUB -DC_SUB 
> -DTINY_SUB -DLBUF32 -DPOP3_DOORS -DEMPIRE_DOORS -DMUSH_DOORS -DQDBM 
> -DSQLITE -DSBUF64 -DENABLE_DOORS -DEXAMPLE_DOOR_CODE 
> -DENABLE_WEBSOCKETS -DCRYPT_GLIB2 -DPCRE_SYSLIB  -DMUXCRYPT 
> -DNODEBUGMONITOR -DSECURE_SIDEEFFECT -DPARIS -DBANGS -DMARKER_FLAGS 
> -DZENTY_ANSI -DEXPANDED_QREGS -DREALITY_LEVELS -DATTR_HACK 
> -DENABLE_COMMAND_FLAG -DPROG_LIKEMUX -DPLUSHELP -DUSECRYPT 
> -DSOFTCOM -DMUX_INCDEC -DTINY_U -DUSE_SIDEEFFECT -Wall -DHAS_OPENSSL 
> -I/usr/include/mysql -I/usr/include/mysql/.. -Wall   -DMUSH_BUILD_DATE="\"`cat date.txt`\"" 
> -DRWHO_IN_USE   -DCACHE_OBJS -I../hdrs   -c functions.c

**Comment by mrsenile** [comment]
functions.c is a massive file so it'll pause a bit longer on that specific file as compilers have to cache all the data in the linker as it compiles it.  This is expected behavior.  It can take up to half a minute or so even on faster hardware.

Of interest, clang seems to compile it faster than gcc.

**Comment by mdziczkowski** [comment]
I used the orginally rhost code, so it was there set for gcc ;-p

Note: sorry if my questions sound sometimes stupid, but I just switched to rHost ;)

**Comment by mdziczkowski** [comment]
UPDATE: I had found a way to speed-up the making procedure. I needed only to edit few Makefiles in the `src` directory and edit one line of code in each.

I needed only to replace the calue of `OPTIM` and set it's value to -O3 or -O4 (in newer versions)
