### ISSUE TITLE
Crash dump after attempting to restart an fresh server after shutting it down

### ISSUE THREAD

**Issue by mdziczkowski** [RhostMUSH/trunk#87]
After starting the fresh server and then attempting to restart it, I recieved a following crash dump as in the attached file. Any ideas pf solving it to prevent from causing ?
[dump.txt](https://github.com/RhostMUSH/trunk/files/6334891/dump.txt)

**Comment by Chalice** [comment]
Yes - as the text says beneath the dump, you did not @shutdown your mush from in-game, but killed the process :)

You need to open your netrhost.conf file and change the debug_id to some other number if you wish to immediately restart the MU* after a kill. It's highly advised to use @shutdown or a kill -s 12 <pid>. Signal 12 is SIGUSR2 which will cause a proper @shutdown within the game.

**Comment by mrsenile** [comment]
If you're absolutely sure nothing is using that debug_id shared memory, you can also do Startmush -f which force re-attaches to the shared memory segment for the process.

If you have another mush using that shared memory, it can (and will) cause issues to the stack tracer.

**Comment by mdziczkowski** [comment]
> Yes - as the text says beneath the dump, you did not @shutdown your mush from in-game, but killed the process :)
> 
> You need to open your netrhost.conf file and change the debug_id to some other number if you wish to immediately restart the MU* after a kill. It's highly advised to use @shutdown or a kill -s 12 . Signal 12 is SIGUSR2 which will cause a proper @shutdown within the game.

Strange... I had used the @shutdown in my client. I don't know that it act like it got killed with Signal 9....

That's not a normal server behaviour because when it shut down (or get killed if unrensponsible to the input), it shouldn't leave such thing behind...

**Comment by mrsenile** [comment]
@shutdown should have cleanly shut the game down and closed off the shared memory.

The backup_flat running isn't a big issue, and when you restart the mush with Startmush it cleans itself up after the fact.  Shutting down the mush won't kill the script as the script is an entirely separate process from the mush.  I could make the backup_flat a bit smarter and have it shutdown if it detects the mush process stops, but this would require a much tighter loop (like maybe checking every minute?  5 minutes?  ergo more overhead, but as it does a 14+ hour loop the overhead of it running is as close to nonexistant as you can have it.  So it's a bit of a trade off between constant checks and higher load usage to long sleeps.

If you don't want the background process running you can turn backup_flat.sh into a one-time run (backup_flat.sh -s).  Which you could write as an execscript() and put in the mush cron.

There's several ways to currently solve this depending on the needs of the user.

**Comment by mdziczkowski** [comment]
about the backup flat script... shouldn't it be run periodically (only to create a backup of the database) instead running whole time?

**Comment by Chalice** [comment]
Well, the script does not get startet by the MU* Server itself. It gets started by the ./Startmush wrapper that starts both. The only way not to have the script running would be to have people create a Cronjob for it - this way is easier :)

**Comment by mrsenile** [comment]
The backup script also will only ever have one process running at a given time.  It will auto-kill any existing process when you restart the mush.

The overhead of this script running, if your mush does crash, is minimal since the overhead is essentially a 'sleep' command in the queue.  Which is about as low-latency as you can get.

There's work arounds as Ambrosia suggested if one wishes to use a cron based backup instead.

Marking this closed.
